name: Propuesta de cambio
description: Crear una propuesta formal de cambio técnico
title: "[Propuesta]: "
labels: [estado:pendiente]
assignees: []

body:
  - type: dropdown
    id: tipo-cambio
    attributes:
      label: Tipo de cambio
      description: Selecciona el tipo de cambio propuesto
      options:
        - Nuevo adaptador
        - Mejora de adaptador existente
        - Modificación de interfaz
      multiple: false
    validations:
      required: true

  - type: textarea
    id: descripcion-tecnica
    attributes:
      label: Descripción técnica
      description: Explica detalladamente los cambios propuestos
    validations:
      required: true

  - type: textarea
    id: justificacion
    attributes:
      label: Justificación funcional o valor agregado
      description: Indica el valor funcional del cambio (ej. estándar de industria, mejora de interoperabilidad, etc.)
    validations:
      required: true

  - type: textarea
    id: verificacion
    attributes:
      label: Verificación de propuesta existente
      description: Explica cómo has validado que no existe una propuesta equivalente
    validations:
      required: true

  - type: checkboxes
    id: alcance
    attributes:
      label: Alcance del cambio
      description: Selecciona las áreas que afecta
      options:
        - label: Interfaz
        - label: Adaptador
        - label: Interfaz y Adaptador
